### PR TITLE
Rule Generation Modification/Fool Proofing Modifications

### PR DESCRIPTION
**Pull request by amidos2006**
It looks like lots of changes but its nothing. The code refactor change the indentation for couple of files.
Changes:
- Fool Proofing
- Constructive Rule Generation
- Random Rule Generation
- Level Analyzer Improving

### CODE REVIEW

**Comment by diegopliebana** [comment]
Hi. Even if this is due to indentation, we cannot make this commit. It also makes impossible to track back any changes in the code through the commits. Also, the automatic indentation creates a lot of unnecessary lines that make the files bigger and bigger. And another thing that happened and I had to fix manually a few days ago: the whole ArcadeMachine.java was incorrectly indented (no indentation at all, actually), so on top of that, the whole commit didn't reflect the real changes that were made.

Is it possible to leave the indentation as it was before (and that there's no auto-indentation in the future?) Then I'll merge.

**Comment by amidos2006** [comment]
Can you accept just the classes I modified or should I reset the files that has changed?

**Comment by amidos2006** [comment]
Next time, I will try not to press the refactor button 😄 
I just press it without noticing.

**Comment by diegopliebana** [comment]
I'm not sure if I can accept to merge only specific classes. Do you have a list of the classes that have changed? I hope it's not too hard to reset the others...

**Comment by amidos2006** [comment]
Let me check if I can list them:
+ ForwardModel.java
+ SLDescription.java
+ Logger.java
+ Message.java
+ Align.java
+ PullWithIt.java
+ TeleportToExit.java
+ LevelAnalyzer.java
+ RuleGenMachine.java
+ TestRuleGeneration.java
+ src/tracks/ruleGeneration/constructiveRuleGenerator/RuleGenerator.java
+ src/tracks/ruleGeneration/randomRuleGenerator/RuleGenerator.java
+ src/core/game/BasicGame.java
+ src/core/game/Game.java

**Comment by diegopliebana** [comment]
Yeah, okay, but those have changed too much (for instance, Game). I think it'd be better to make a new pull request with the code indented as it was before.

**Comment by amidos2006** [comment]
Now it drops from 23 file to the 16 files I modified :)

**Comment by amidos2006** [comment]
I think these are the files I modified for fool proofing and improving the rule generation framework

**Comment by diegopliebana** [comment]
I've merged it, although Game was still modified in 2000 lines...

**Comment by amidos2006** [comment]
Sorry for that but I was trying to reset the file but I made also lots of modifications in it and I was afraid to lose them :S next time, I will try to resist hitting the refactor key :D thanks a lot Diego :)

**Pull request merged**
