### PR TITLE
Re-Implementation Optimizations

### PR DESCRIPTION
**Pull request by DennisSoemers**
Hey,

Since the optimizations recently merged into the optimizations branch seem to have disappeared for unknown reasons, and I wanted to start using them for my own experiments, I decided to re-implement them. I figured I'd send a pull request again since I suppose that is the easiest way for you to add them back into the framework.

I went through the changes visible in https://github.com/EssexUniversityMCTS/gvgai/commit/37b492105f2cb72034233b9d6d031fb4fb4485b7 and re-applied them, taking into consideration any other changes in the code that happened in between. For instance, I included the is_disabled() checks that weren't there previously in the new eventHandling() code. 

I removed the thinkingTime boolean from VGDLSprite again. I am aware that this causes a little bit of extra code to run in preMovement() due to the recent animation addition, but this is fairly cheap code; it's not loading images. The optimization with the template sprites means that postProcess(), and therefore loadImages(), is rarely called anymore, and therefore the use of the thinkingTime boolean is not really necessary anymore and in fact breaks the graphics in some cases (in cases where a template object is created when the flag is set to false).

A few of the more recently added classes may still need modifications to use .equals() instead of == for comparing Vectors/Directions. For instance, ontology.avatar.oriented.OngoingTurningAvatar.java still needs such a change (I did not fix these). Classes that already existed in the optimizations branch when I originally implemented the optimizations have been fixed already in this pull request (for instance, ontology.avatar.oriented.OngoingAvatar.java).

### CODE REVIEW

**Comment by diegopliebana** [comment]
Thanks for this Dennis,

I've just accepted the request. I'll run some quick tests again to check everything is fine (this time making sure that the changes have not evaporated in the way).

Best,
Diego.

**Comment by DennisSoemers** [comment]
@diegopliebana 

I've discovered a bug caused by the optimization using the templateSprites array that is relatively easy to fix. I noticed that, when using the ArcadeMachine to play all levels of the Painter game, the second level (index 1) is bugged for some reason after playing through level 0 (if starting from level 1 it does work fine). I am not entirely sure what causes this bug, but it can be fixed easily, by adding the following code to core.game.Game.reset():

`
for(int i = 0; i < templateSprites.length; ++i)
{
    templateSprites[i] = null;
}
`

**Comment by diegopliebana** [comment]
Thanks Dennis,

Just added that piece of code to the reset() function. It does make sense that the template sprites need to be reset too, the error could have been affecting other games as well.

Best,
Diego.

**Comment by DennisSoemers** [comment]
@diegopliebana 

I've recently run 200 runs of every game, and there seems to be a rare issue in the two lasers games (lasers and lasers2). Sometimes, the game starts printing ''Sprite limit reached'' messages, indicating that there are over 10K sprites. Out of those 200 runs per game it happened once on lvl1 and once on lvl2 for lasers, and once on lvl2 for lasers2.

I went looking into those games and did discover some bug that can be fixed with a single line of code, related to the template sprites optimization. Currently, if the avatar pushes a box into a wall or a lasercannon, the "undoAll" effect triggers and that causes some of the laser cannons to quickly shoot individual lasers in an incorrect direction. In core.game.Game.addSprite, there is the following line of code after storing a sprite in the templateSprites array (line 1651 in my version of the code):

`newSprite.lastrect = new Rectangle(newSprite.rect);`

And the following line should be added after it to fix the bug with the undoAll effect working incorrectly:

`newSprite.lastrect = new Rectangle(newSprite.rect);`

I am not yet sure if this is what caused the number of sprites to grow out of control, but I do suppose it could be a cause if that bug caused lasers to end up outside the bounds of the map somehow.

**Comment by diegopliebana** [comment]
Hi Dennis,

I haven't seen that error in my tests, but it's worth to double check. I'm not sure if you've pasted the correct line here, though. There's no:

`newSprite.lastrect = new Rectangle(newSprite.rect);`

in Game.java. 

Also, would you mind sharing the results of those 200 runs on each game?

Thanks,
Diego.

**Comment by DennisSoemers** [comment]
@diegopliebana 

You're right, I meant to say that the line I pasted twice there should be newly added after this line that already exists:

`newSprite.setRect(position, new Dimension(block_size, block_size));`

What do you mean with sharing my results on those 200 runs per game? If you mean the number of iterations for the sample MCTS controller, I didn't run that. These were experiments with some different versions of my own agent.

**Comment by diegopliebana** [comment]
Thanks Dennis,

Line added and bug fixed. Never mind your results, I thought you were using one of the sample controllers.

Best,
Diego.

**Pull request merged**
