### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by DennisSoemers**
This pull request contains the two optimizations I mentioned having implemented and tested in issue #34. The improvements I obtained in the tests I mentioned in the issues seem significant enough to me (majority of games improved performance, some of them also a rather large magnitude of improvement, only a few a small decrease in performance). Those were obtained on relatively slow hardware though (2.4 GHz processors), and on my own development machine (2.66 GHz) the improvements appeared even larger in some quick tests, but did not have time to run all of the games extensively on that machine.

I attempted to change anything back that was unintentional (largely changes in the imports that my IDE automatically applied), so everything that is still changed should be intentional.

### CODE REVIEW

**Comment by diegopliebana** [comment]
Thanks Dennis,

I'll have a look at this (and the other PDFs that you sent) when I have a minute and then accept your pull request.

Many thanks for your work on this,
Diego.

**Comment by DennisSoemers** [comment]
@diegopliebana 

I was previously working mostly with the games in the first set of 10 games, and have only recently been looking into more games. Looking into other games in more details (specifically, some of the slow ones with lots of lasers from the last set, like Lasers2 and FactoryManager) made me think of something else that is likely a significant performance boost on these types of games.

It should be really simple to implement. In core.game.Game.eventHandling(), there is no reason at all for the first two large loops, which process Time effects and EOS effects, to use the whole buckets system. Currently, those loops collect all these sprites and place them in the buckets, which is fairly expensive still, but then don't make any use at all of the space partitioning and loop through all the sprites again to process Time or EOS effects. So, I'd suggest one of the following two changes for these 2 loops:

1) collect the sprites in a simple ArrayList instead of the whole complicated bucket system, OR
2) don't collect them at all. Just do the necessary checks (kill_list.contains() for both, and isAtEdge() for EOS), and execution of effect, directly in the place where the current code does bucketList[intId].add(sp).

This would probably both make the code shorter and more readable, and also much more efficient in a game like FactoryManager, where I've quickly checked and it's easily possible to have 60+ laser objects existing at the same time, which in the current code leads to 60+ objects being needlessly placed in buckets in every eventHandling call

Do you want me to implement this in my branch first, before you pull request, and extensively test as well? I'd personally feel like extensive testing is not necessary in this case since it seems like a straightforward change, but I could look into it if you prefer.

**Comment by diegopliebana** [comment]
Hi Dennis,

Yes, please, implement this in the same branch and I'll do the merge. I don't think we'll need testing for this, I plan to do a double check too.

Many thanks,
Diego.

**Comment by DennisSoemers** [comment]
Alright, I have just pushed the change. I tested very quickly on a few games (Aliens, Frogs and Factory Manager) and the gameplay still seems to be correct to me / nothing seems to be broken.

**Comment by diegopliebana** [comment]
Many thanks Dennis,

I plan to work on this very soon, I'll keep you posted.

Best,
Diego.

**Comment by DennisSoemers** [comment]
@diegopliebana 

I was just looking at the twoPlayersTrack branch, but my optimizations do not seem to be in there currently. I can still see the merged changes on this page:

https://github.com/EssexUniversityMCTS/gvgai/commit/37b492105f2cb72034233b9d6d031fb4fb4485b7?diff=unified

But that commit is nowhere to be found on either the commits page of the optimizations branch or the twoPlayersTrack branch (see these two pages: https://github.com/EssexUniversityMCTS/gvgai/commits/optimizations and https://github.com/EssexUniversityMCTS/gvgai/commits/twoPlayersTrack ).

Do you happen to have any idea what happened to the optimizations?

**Comment by diegopliebana** [comment]
Hi Dennis,

Honestly, no idea. I cannot even see some of them in the optimizations branch (i.e. Game.templateSprites[] is nowhere to be seen)...

**Pull request merged**
